### ISSUE TITLE
KHR_texture_transform tiles the occlusionTexture

### ISSUE THREAD

**Issue by silvainSayduck** [google/usd_from_gltf#23]
I have a [glTF model](https://github.com/google/usd_from_gltf/files/3728330/box.gltf.zip) with a  `baseColorTexture` using the `KHR_texture_transform` extension and an `occlusionTexture`.

This is how it looks in the [glTF Viewer](https://gltf-viewer.donmccurdy.com/)
![](https://i.imgur.com/OLnFsbF.png)

Here is how my [converted USDZ](https://github.com/google/usd_from_gltf/files/3728328/box.usdz.zip) looks like
![](https://i.imgur.com/uL4pd3l.jpg)

I believe this is not the expected behavior according to the specs, as the maps should be tiled according to their own `KHR_texture_transform` extension values, and the `occlusionTexture` should thus not be tiled.

(On a side note, unless I'm mistaken, it seems that Three's glTF Viewer also does not respect the specs, as it seem to never tile the `occlusionTexture` and tile all other maps based on the `baseColorTexture` `KHR_texture_transform` values.)

**Comment by C0DED00D** [comment]
Unfortunately, this is the expected behavior. Because Apple's viewer only supports 1 set of UVs, we implemented the texture transform by baking the transformation into the single UV coordinate set. The side effect of that is that the transform is applied to all textures. :( I realize that this limits the usefulness of the Texture Transform Extension, but I'm not sure there is a better way to provide the functionality - at least until a future version of iOS supports multiple texture coordinates. 

I will update our documentation to clarify this. Sorry for the trouble! Please re-open the issue if you have any more questions!

**Comment by silvainSayduck** [comment]
Hi,

And thank you for the quick and clear answer. This basically leaves us with the choice of "pretiling" our textures (poor texture quality) or not use occlusion maps... Not ideal, but I do understand it's on Apple's side.
Thanks a lot for the great work!
