### ISSUE TITLE
Improved commit messages

### ISSUE THREAD

**Issue by StephenRadachy** [google/usd_from_gltf#45]
👋Truly amazing and useful tool y'all built.

![you're awesome](https://media1.tenor.com/images/07feba4572471b21fd4258b6af83c9c4/tenor.gif?itemid=4158682)

Moving forward, can we have more descriptive commit messages?

Most of the commits on the [master branch](https://github.com/google/usd_from_gltf/commits/master) are `Internal change` or just generally not representative of what the commit relates to.

It would be awesome to have a bit more context as to why you're making a change instead of having to read through the diff and guess.

Thanks!

**Comment by hujasonx** [comment]
Thanks for bringing this up. I assumed that this was an unavoidable result of us using a tool to keep an internal repo and this public repo in sync. Turns out (just found out about this like right now), that tool actually has a way to set the public-facing commit message. From now on I'll try to set public commit messages with each code change.

Thanks!
Jason
